### ISSUE TITLE
如何使用这份文件？

### ISSUE THREAD

**Issue by neil-wang-global** [lhjandroid/HookFlutterClipBoard#1]
我也在研究TextField剪贴板的合规问题，想avoid掉，然后就看到了这个repo，请问一下这个如何使用呢？

**Comment by lhjandroid** [comment]
> 我也在研究TextField剪贴板的合规问题，想avoid掉，然后就看到了这个repo，请问一下这个如何使用呢？

如果你是混合开发如果已经继承FlutterFragmentActivity做了一些修改那重写
```
 @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        FlutterClipBoardHelper.hookClipBoard(flutterEngine);
 }
```
别的方式在你注册channel的地方拿到FlutterEngine然后调用
`FlutterClipBoardHelper.hookClipBoard(flutterEngine);`

**Comment by neil-wang-global** [comment]
It works.👍👍
